#include "handleWebServer.h"

void showWiFiMode(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Wifi mode is changing while the middle led is on, please wait until it is off and select the right WiFi (SSID) before selecting the home/help page\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<a href='/help/'>Go to the home/help page</a>\r\n";
  result += "\r\n</body>\r\n</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void help(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "<input id=\"EN\" type=\"button\" onclick=\"selectLanguage(this)\" value=\"English\">\r\n";
  result += "<input id=\"NL\" type=\"button\" onclick=\"selectLanguage(this)\" value=\"Nederlands\">\r\n";
  result += "<br><br>\r\n";
  result += "WiFi mode: ";
  if (pSettings->beginAsAccessPoint() == true)
  {
    result += "Access Point\r\n";
    result += "<br>\r\n";
    result += "(url: <a href='http://model.local/' target='_blank'>model.local</a> or <a href='http://192.168.4.1/' target='_blank'>http://192.168.4.1</a>)\r\n";
  }
  else
  {
    result += "Network Station\r\n";
    result += "<br>\r\n";
    result += "(url: <a href='http://model.local/' target='_blank'>model.local</a> or via a local IP address, last known is: <a href='http://";
    result += pSettings->getLastNetworkIP();
    result += "/' target='_blank'>";
    result += pSettings->getLastNetworkIP();
    result += "</a>\r\n";
    result += ")\r\n";
  }  
  result += "<br>\r\n";
  result += "<div id=\"sendMessage\"></div>\r\n";
  result += "<br><br>\r\n";

  result += "Version: <span id='version'></span>\r\n";
  result += " <input id='updateFirmwareButton' type='button' onclick='updateFirmware()' value='Update Firmware'<br>\r\n";
  result += " <div id=\"updateFirmwareMessage\"><div>\r\n";
  result += "<br><br>\r\n";

  result += "Menu\r\n";
  result += "<br><br><br>\r\n";
  result += "<a href='/help/'>help</a> help/home screen\r\n";
  result += "<br><br>\r\n";
  result += "<a href='/device/'>Model settings</a> WiFi mode, Server settings\r\n";
  result += "<br><br>\r\n";
  result += "<a href='/wifi/'>WiFi</a> settings to connect the Model to WiFi\r\n";
  result += "<br><br>\r\n";

  result += "<script>\r\n";
  result += "  document.getElementById(\"version\").innerHTML = \"";
  result += pSettings->getFirmwareVersion();
  result += "\";\r\n";
  result += "  function updateFirmware() {\r\n";
  result += "    document.getElementById(\"updateFirmwareButton\").disabled = true\r\n";
  result += "    document.getElementById(\"updateFirmwareMessage\").innerHTML = \"Please refresh this page after about 1 minute\"\r\n";
  result += "    var params = \"name=update\";\r\n";
  result += "    sendUpdateFirmware(params, \"/update/\");\r\n";
  result += "  };\r\n";
  result += "</script>\r\n";

  result += "<script>\r\n";
  result += "  function selectLanguage(component) {\r\n";
  result += "    var params = \"name=help\" + \"&language=\" + component.id;\r\n";
  result += "    document.getElementById(\"NL\").disabled = true;\r\n";
  result += "    document.getElementById(\"EN\").disabled = true;\r\n";
  result += "    sendData(params, \"/language/\");\r\n";
  result += "  }\r\n";
  result += "  function sendData(data, path) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", path);\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "    //xhr.setRequestHeader(\"Content-Type\", \"application/json\");\r\n";
  result += "   document.getElementById(\"sendMessage\").innerHTML = \"Please wait\";\r\n";
  result += "    xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "     var myResponseText = \"\";\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "        window.location.reload();\r\n";
  //result += "       myResponseText = this.responseText || \"\";\r\n";
  result += "     }\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "       myResponseText = this.statusText || \"\";\r\n";
  result += "      }\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";

  result += "  function sendUpdateFirmware(data, path) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", path);\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "   document.getElementById(\"sendMessage\").innerHTML = \"Please wait\";\r\n";
  result += "    xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "     var myResponseText = \"\";\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "        window.location.reload();\r\n";
  //result += "       myResponseText = this.responseText || \"\";\r\n";
  result += "     }\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "       myResponseText = this.statusText || \"\";\r\n";
  result += "      }\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";

  result += "</script>\r\n";

  result += "\r\n</body>\r\n</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}


void showSavedSettings(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Settings\r\n";
  result += "<br><br>\r\n";
  result += "opgeslagen deviceKey: \r\n";
  result += pSettings->getDeviceKey();
  result += "\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<a href='/help/'>Go to the home/help page</a>\r\n";
  result += "</body>\r\n";
  result += "</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void device(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML><html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Settings for the Model\r\n";
  result += "<br><br>\r\n";
  result += "<input type=\"radio\" name=\"settings\" onclick=\"displaySettings()\" value=\"device\" checked>Device\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"settings\" onclick=\"displaySettings()\" value=\"targetServer\">Target server\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<div id=\"device\">\r\n";
  result += "    <br>\r\n";
  result += "    Set the WiFi start Mode <input id=\"startWiFiMode\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryStartModeWiFi();
  result += "\" value=\"reset\">\r\n";
  result += "    <br>\r\n";
  result += "    <input type=\"radio\" name=\"startWiFiMode\" value=\"ap\" ";
  result += (pSettings->beginAsAccessPoint() == true)?"checked":"";
  result += "> start as Access Point\r\n";
  result += "    <br>\r\n";
  result += "    <input type=\"radio\" name=\"startWiFiMode\" value=\"network\" ";
  result += (pSettings->beginAsAccessPoint() == true)?"":"checked";
  result += "> start as Network Station\r\n";
  result += "    <br><br>\r\n";
  result += "  After 'Save' wait for confirmation.\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"deviceButton\" type=\"button\" name=\"deviceButton\" value=\"Save\" onclick=\"saveDevice(this)\">\r\n";
  result += "  <input type=\"button\" name=\"deviceCancelButton\" value=\"Cancel\" onclick=\"cancelSettings()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<div id=\"targetServer\">\r\n";
  result += "    <br>\r\n";
  result += "    Target server\r\n";
  result += "    <br>\r\n";
  result += "  Domain name: <input type=\"text\" name=\"targetServer\" maxlength=\"32\" size=\"33\" placeholder=\"protocol://domain name\" value=\"";
  result += pSettings->getTargetServer();
  result += "\"> Max 32 characters\r\n";
  result += "    <input id=\"targetServer\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryTargetServer();
  result += "\" value=\"reset\">\r\n";
  result += "    <br>\r\n";
  result += "    Port: <input type=\"text\" name=\"targetPort\" min=\"0\" max=\"65536\" maxlength=\"5\" size=\"6\" placeholder=\"port\" title=\"0 - 65536\" value=\"";
  result += String(pSettings->getTargetPort());
  result += "\"  onkeyup=\"checkNumber(this, 'portMessage', 'Invalid counter (0 - 65536)');\">\r\n";
  result += "    <input id=\"targetPort\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += String(pSettings->getFactoryTargetPort());
  result += "\" value=\"reset\">\r\n";
  result += "    <span id=\"portMessage\"></span>\r\n";
  result += "    <br>\r\n";
  result += "    Path: <input type=\"text\" name=\"targetPath\" maxlength=\"16\" size=\"17\" placeholder=\"path\" value=\"";
  result += pSettings->getTargetPath();
  result += "\"> Max 16 characters\r\n";
  result += "    <input id=\"targetPath\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryTargetPath();
  result += "\" value=\"reset\">\r\n";
  result += "  <br><br>\r\n";
  result += "  After 'Save' wait for confirmation.\r\n";
  result += "    <br>\r\n";
  result += "  <input id=\"targetServerButton\" type=\"button\" name=\"targetServerButton\" value=\"Save\" onclick=\"saveTargetServer(this)\">\r\n";
  result += "  <input type=\"button\" name=\"targetServerCancelButton\" value=\"Cancel\" onclick=\"cancelSettings()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<br>\r\n";
  result += "<div id=\"sendMessage\"></div>\r\n";
  result += "\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<a href='/help/'>Go to the home/help page</a>\r\n";
  result += "<script>\r\n";
  result += "  function factorySetting(component) {\r\n";
  result += "      var id = component.id || \"\";\r\n";
  result += "      var factoryValue = component.getAttribute(\"reset\");\r\n";
  result += "      var names = document.getElementsByName(id) || [];\r\n";
  result += "      if (names.length > 0) {\r\n";
  result += "        var type = names[0].getAttribute(\"type\");\r\n";
  result += "        if (type == \"radio\")\r\n";
  result += "        {\r\n";
  result += "            for (var i = 0; i < names.length; i++)\r\n";
  result += "            {\r\n";
  result += "                if (names[i].value == factoryValue) {\r\n";
  result += "                    names[i].checked = true;\r\n";
  result += "                };\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        if (type == \"checkbox\")\r\n";
  result += "        {\r\n";
  result += "            var factoryValueArray = factoryValue.split(\",\");\r\n";
  result += "            for (var i = 0; i < names.length; i++)\r\n";
  result += "            {\r\n";
  result += "                names[i].checked = false;\r\n";
  result += "                for (var e = 0; e < factoryValueArray.length; e++)\r\n";
  result += "                {\r\n";
  result += "                    if (names[i].value == factoryValueArray[e].trim()) {\r\n";
  result += "                        names[i].checked = true;\r\n";
  result += "                    }\r\n";
  result += "                }\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        if (type == \"text\")\r\n";
  result += "        {\r\n";
  result += "            names[0].value = factoryValue;\r\n";
  result += "        }\r\n";
  result += "      }\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function checkNumber(component, messageId, message) {\r\n";
  result += "    var buttonId = component.parentNode.id + \"Button\";\r\n";
  result += "  //var validCharacterString = \"0123456789-.\";\r\n";
  result += "  var valid = false;\r\n";
  result += "    if ((component.value >= Number(component.getAttribute(\"min\"))) && (component.value <= Number(component.getAttribute(\"max\")))) {\r\n";
  result += "        valid = true;\r\n";
  result += "    }\r\n";
  result += "    if (valid) {\r\n";
  result += "      document.getElementById(messageId).innerHTML = \"\";\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "    document.getElementById(messageId).innerHTML = message;\r\n";
  result += "    }\r\n";
  result += "    document.getElementById(buttonId).disabled = !valid;\r\n";
  result += "    return valid;\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function cancelSettings() {\r\n";
  result += "  window.location.reload();\r\n";
  result += "  }\r\n";
  result += "  function sendData(data) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", \"/deviceSettings/\");\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "    //xhr.setRequestHeader(\"Content-Type\", \"application/json\");\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = \"Please wait\";\r\n";
  result += "      xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "        var myResponseText = \"\";\r\n";
  result += "        if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "          myResponseText = this.responseText || \"\";\r\n";
  result += "        }\r\n";
  result += "        if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "          myResponseText = this.statusText || \"\";\r\n";
  result += "        }\r\n";
  result += "        document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "      }\r\n";
  //result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveDevice(content) {\r\n";
  result += "        var children = content.parentNode.childNodes;\r\n";
  result += "        var startWiFiMode = \"\";\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"startWiFiMode\") {\r\n";
  result += "                if (children[i].checked == true) {\r\n";
  result += "                    startWiFiMode = children[i].value || true;\r\n";
  result += "                }\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        var params = \"name=device\" + \"&startWiFiMode=\" + startWiFiMode;\r\n";
  result += "        sendData(params);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveTargetServerData(content) {\r\n";
  result += "        var children = content.parentNode.childNodes;\r\n";
  result += "        var allowSendingData = \"\";\r\n";
  result += "        var isOpen = \"\";\r\n";
  result += "        var showData = \"\";\r\n";
  result += "        var message = \"\";\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"allowSendToTarget\") {\r\n";
  result += "                allowSendingData = children[i].checked == true;\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        children = document.getElementById(\"allowed\").childNodes;\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"entree\") {\r\n";
  result += "                if (children[i].checked == true) {\r\n";
  result += "                    isOpen = children[i].value || \"\";\r\n";
  result += "                }\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"showDataOnTarget\") {\r\n";
  result += "                showData = children[i].checked == true;\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        children = document.getElementById(\"showMessage\").childNodes;\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"message\") {\r\n";
  result += "                message = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        var params = \"name=targetServerData\" + \"&allowSendingData=\" + allowSendingData + \"&isOpen=\" + isOpen + \"&showData=\" + showData + \"&message=\" + encodeURIComponent(message);\r\n";
  result += "        sendData(params);\r\n";
  result += "    }\r\n";
  result += "\r\n";
  result += "  function saveTargetServer(content) {\r\n";
  result += "        var children = content.parentNode.childNodes;\r\n";
  result += "        var targetServer = \"\";\r\n";
  result += "        var targetPort = \"\";\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"targetServer\") {\r\n";
  result += "                targetServer = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"targetPort\") {\r\n";
  result += "                targetPort = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"targetPath\") {\r\n";
  result += "                targetPath = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        var params = \"name=targetServer\" + \"&targetServer=\" + encodeURIComponent(targetServer) + \"&targetPort=\" + targetPort + \"&targetPath=\" + encodeURIComponent(targetPath);\r\n";
  result += "        sendData(params);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function loadWiFiNetworkList() {\r\n";
  result += "  var xhttp = new XMLHttpRequest();\r\n";
  result += "  xhttp.onreadystatechange = function() {\r\n";
  result += "    if (this.readyState == 4 && this.status == 200) {\r\n";
  result += "      document.getElementById(\"ssidList\").innerHTML = this.responseText;\r\n";
  result += "    }\r\n";
  result += "  };\r\n";
  result += "  xhttp.open(\"GET\", \"/networkssid/\", true);\r\n";
  result += "  xhttp.send();\r\n";
  result += "}\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function allowSendToTargetCheck(content) {\r\n";
  result += "    if (content.checked == true) {\r\n";
  result += "        document.getElementById(\"allowed\").style.display=\"block\";\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "        document.getElementById(\"allowed\").style.display=\"none\";\r\n";
  result += "    };\r\n";
  result += "}\r\n";
  result += "\r\n";
  result += "function showDataOnTargetCheck(content) {\r\n";
  result += "    if (content.checked == true) {\r\n";
  result += "        document.getElementById(\"showMessage\").style.display=\"block\";\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "        document.getElementById(\"showMessage\").style.display=\"none\";\r\n";
  result += "    };\r\n";
  result += "}\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function displaySettings() {\r\n";
  result += "var ele = document.getElementsByName('settings');\r\n";
  result += "\r\n";
  result += "  for(i = 0; i < ele.length; i++) {\r\n";
  result += "    if(ele[i].checked) {\r\n";
  result += "      document.getElementById(ele[i].value).style.display=\"block\";\r\n";
  result += "//      if (ele[i].value == 'network') {\r\n";
  result += "//        loadWiFiNetworkList();\r\n";
  result += "//      }\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "      document.getElementById(ele[i].value).style.display=\"none\";\r\n";
  result += "    }\r\n";
  result += "  }\r\n";
  result += "}\r\n";
  result += "displaySettings();\r\n";
  result += "</script>\r\n";
  result += "</body>\r\n";
  result += "</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void wifi(ESP8266WebServer &server, Settings * pSettings, WiFiSettings * pWiFiSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Don't want to share with internet or no WiFi available? Choose AccessPoint\r\n";
  result += "<br>\r\n";
  result += "You want to share with internet and have WiFi available? Choose Network\r\n";
  result += "<br><br>\r\n";
  result += "<input type=\"radio\" name=\"wifi\" onclick=\"displayWiFiMode()\" value=\"ap\">Access Point\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"wifi\" onclick=\"displayWiFiMode()\" value=\"network\">Network Station\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"wifi\" onclick=\"displayWiFiMode()\" value=\"erase\">Go to Erase-WiFi-Data menu\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<div id=\"ap\">\r\n";
  result += "  Clients can get access to this Access Point using the SSID and password entered below\r\n";
  result += "  <br>\r\n";
  result += "  An empty SSID will result in a default SSID for the Model\r\n";
  result += "  <br>\r\n";
  result += "  An empty password will result in an unencrypted, open Access Point\r\n";
  result += "  <br>\r\n";
  result += "  SSID: <input type=\"text\" name=\"ssid\" maxlength=\"32\" size=\"33\" placeholder=\"";
  if (pWiFiSettings->getAccessPointSSID() == "")
  {
    result += "SSID";
  }
  else
  {
    result += pWiFiSettings->getAccessPointSSID();
  }
  result += "\" value=\"";
  result += pWiFiSettings->getAccessPointSSID();
  result += "\">\r\n";
  result += "  <br>\r\n";
  result += "  Password: <input type=\"password\" name=\"password\" maxlength=\"32\" size=\"33\" placeholder=\"";
  if (pWiFiSettings->getAccessPointPassword() == "")
  {
    result += "password";
  }
  else
  {
    result += pWiFiSettings->getAccessPointPassword();
  }
  result += "\" value=\"";
  result += pWiFiSettings->getAccessPointPassword();
  result += "\" onkeyup=\"checkURIComponent(this, 'apPasswordMessage', 'Invalid password character');\">\r\n";
  result += " <span id=\"apPasswordMessage\"></span>\r\n";
  result += "  <br><br>\r\n";
  result += "  After 'Save' wait for confirmation.\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"apButton\" type=\"button\" name=\"apButton\" value=\"Save\" onclick=\"saveAP(this)\">\r\n";
  result += "  <input type=\"button\" name=\"apCancelButton\" value=\"Cancel\" onclick=\"cancelWiFi()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<div id=\"network\">\r\n";
  result += "  Connect to one of the WiFi networks below\r\n";
  result += "  <br><br>\r\n";
  result += "  <span id=\"ssidList\">Please wait for a list or a message to show here</span>\r\n";
  result += "  <br><br>\r\n";
  result += "  <span id=\"selectedWiFiPassword\">";
  result += "Give the password for the selected WiFi network <span id=\"selectedWiFi\"></span>\r\n";
  result += "     <br>\r\n";
  result += "     Password: <input type=\"password\" name=\"password\" maxlength=\"32\" size=\"33\" placeholder=\"password\" value=\"";
  result += "\" onkeyup=\"checkURIComponent(this, 'networkPasswordMessage', 'Invalid password character');\">\r\n";
  result += "     <br><br>\r\n";
  result += "  </span>\r\n";
  result += "  After 'Save' wait for confirmation.\r\n";
  result += "  <br>\r\n";
  result += "   <input id=\"networkButton\" type=\"button\" name=\"networkButton\" value=\"Save\" onclick=\"saveNetwork(this)\">\r\n";
  result += "   <input type=\"button\" name=\"networkCancelButton\" value=\"Cancel\" onclick=\"cancelWiFi()\">\r\n";
  result += "  <span id=\"networkPasswordMessage\"></span>\r\n";
  result += "</div>\r\n";
  result += "<div id=\"erase\">\r\n";
  result += "  !!!Warning!!!\r\n";
  result += "  <br><br>\r\n";
  result += "  A click on an Erase button will immediately erase saved data! Your current connection will stay alive.\r\n";
  result += "  <br><br>\r\n";
  result += "Do NOT Erase and <input type=\"button\" name=\"networkButton\" value=\"Cancel\" onclick=\"cancelWiFi()\">\r\n";
  result += "  <br><br>\r\n";
  result += "  <input id=\"eraseAPData\" type=\"button\" name=\"eraseAPDataButton\" value=\"Erase\" onclick=\"eraseWiFiData(this)\"> Erase Access Point data, will result in an unencrypted, open Access Point\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"eraseNetworkData\" type=\"button\" name=\"eraseNetworkDataButton\" value=\"Erase\" onclick=\"eraseWiFiData(this)\"> Erase Network data\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"eraseWiFiData\" type=\"button\" name=\"eraseWiFiDataButton\" value=\"Erase\" onclick=\"eraseWiFiData(this)\"> Erase Access Point AND Network data\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "  <br>\r\n";
  result += "<div id=\"sendMessage\"></div>\r\n";
  result += "\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<a href='/help/'>Go to the home/help page</a>\r\n";
  result += "<script>\r\n";
  result += "function checkURIComponent(component, messageId, message) {\r\n";
  result += "  var invalidCharacterArray = [\"&\"]\r\n";
  result += "  var buttonNodeId = component.parentNode.id;\r\n";
  result += "  if (buttonNodeId == \"selectedWiFiPassword\") {\r\n";
  result += "    buttonNodeId = component.parentNode.parentNode.id;\r\n";
  result += "  };\r\n";
  result += "  var buttonId = buttonNodeId + \"Button\"\r\n";
  result += "   var valid = true;\r\n";
  result += "   for (var c = 0; c < invalidCharacterArray.length; c++) {\r\n";
  result += "    if (component.value.indexOf(invalidCharacterArray[c]) > -1) {\r\n";
  result += "      valid = false;\r\n";
  result += "      break;\r\n";
  result += "    };\r\n";
  result += "  };\r\n";
  result += "  if (valid) {\r\n";
  result += "    document.getElementById(messageId).innerHTML = \"\";\r\n";
  result += "  }\r\n";
  result += "  else {\r\n";
  result += "    document.getElementById(messageId).innerHTML = message;\r\n";
  result += "  }\r\n";
  result += "  document.getElementById(buttonId).disabled = !valid;\r\n";
  result += "   return valid;\r\n";
  result += "}\r\n";
  result += "  function cancelWiFi() {\r\n";
  result += "    window.location.reload();\r\n";
  result += "  }\r\n";
  result += "  function sendData(data) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", \"/wifiConnect/\");\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "    //xhr.setRequestHeader(\"Content-Type\", \"application/json\");\r\n";
  result += "   document.getElementById(\"sendMessage\").innerHTML = \"Please wait\";\r\n";
  result += "    xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "     var myResponseText = \"\";\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "       myResponseText = this.responseText || \"\";\r\n";
  result += "     }\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "       myResponseText = this.statusText || \"\";\r\n";
  result += "      }\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveAP(content) {\r\n";
  result += "    var children = content.parentNode.childNodes;\r\n";
  result += "    var ssid = \"\";\r\n";
  result += "    var password = \"\";\r\n";
  result += "    for (var i = 0; i < children.length; i++) {\r\n";
  result += "      if (children[i].name == \"ssid\") {\r\n";
  result += "        ssid = children[i].value || \"\";\r\n";
  result += "      }\r\n";
  result += "      if (children[i].name == \"password\") {\r\n";
  result += "        password = children[i].value || \"\";\r\n";
  result += "      }\r\n";
  result += "    }\r\n";
  result += "    var params = \"name=ap\" + \"&ssid=\" + ssid + \"&password=\" + password;\r\n";
  result += "    sendData(params);\r\n";
  result += "    //var json_upload = JSON.stringify({name:\"ap\", ssid:ssid, password:password});\r\n";
  result += "    //sendData(json_upload);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveNetwork(content) {\r\n";
  result += "    var children = document.getElementById(\"selectedWiFiPassword\").childNodes;\r\n";
  result += "    var ssid = document.getElementById(\"selectedWiFi\").innerHTML;\r\n";
  result += "    var password = \"\";\r\n";
  result += "    for (var i = 0; i < children.length; i++) {\r\n";
  result += "      if (children[i].name == \"password\") {\r\n";
  result += "        password = children[i].value || \"\";\r\n";
  result += "      }\r\n";
  result += "    }\r\n";
  result += "    var params = \"name=network\" + \"&ssid=\" + ssid + \"&password=\" + password;\r\n";
  result += "    sendData(params);\r\n";
  result += "    //var json_upload = JSON.stringify({name:\"network\", ssid:ssid, password:password});\r\n";
  result += "    //sendData(json_upload);\r\n";
  result += "  }\r\n";
  result += "  function eraseWiFiData(content) {\r\n";
  result += "  var params = \"name=erase\" + \"&target=\" + content.id;\r\n";
  result += "      sendData(params);\r\n";
  result += "  }\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";

  result += "function showNetworkList(networks) {\r\n";
  result += "  var showNetworkList = [];\r\n";
  result += "  var showNetwork = \"\";\r\n";
  result += "  var networkList = (new Function(\"return [\" + networks + \"];\")());\r\n";
  result += "  networkList.sort((a,b) => (a.dBm > b.dBm) ? 1: (a.dBm === b.dBm) ? ((a.ssid > b.ssid) ? 1: -1) : -1);\r\n";
  result += "  networkList = networkList.filter(function(e) { return e.dBm > -80});\r\n";
  result += "  sortedList = [...networkList].reverse();\r\n";
  result += "  for (var key in sortedList) {\r\n";
  result += "    var value = sortedList[key]\r\n";
  result += "    showNetworkList.push(Object.values(value)[0]);\r\n";
  result += "  }\r\n";
  result += "  var uniqueShowNetworkList = [...new Set(showNetworkList)];\r\n";
  result += "  for (var key in uniqueShowNetworkList) {\r\n";
  result += "    showNetwork += \"<div>\" + uniqueShowNetworkList[key] + \"</div>\";\r\n";
  result += "  }\r\n";
  result += "  if (showNetwork == \"\") {\r\n";
  result += "    showNetwork = \"No WiFi signal available\"\r\n";
  result += "  }\r\n";
  result += "  else {\r\n";
  result += "    document.getElementById(\"selectedWiFiPassword\").style.display=\"block\"\r\n";
  result += "  }\r\n";
  result += "  document.getElementById(\"ssidList\").innerHTML = showNetwork;\r\n";
  result += "}\r\n"; 
  result += "function selectNetworkSSID(content) {\r\n";
  result += "  ssid = \"\"\r\n";
  result += "  if (content.name == \"networkSSID\") {\r\n";
  result += "    ssid = content.value;\r\n";
  result += "  }\r\n";
  result += "  document.getElementById(\"selectedWiFi\").innerHTML = ssid;\r\n";
  result += "}\r\n";
  result += "function loadWiFiNetworkList() {\r\n";
  result += "  var xhttp = new XMLHttpRequest();\r\n";
  result += "  xhttp.onreadystatechange = function() {\r\n";
  result += "    if (this.readyState == 4 && this.status == 200) {\r\n";
  result += "      showNetworkList(this.responseText);\r\n";
  result += "    }\r\n";
  result += "  };\r\n";
  result += "  xhttp.open(\"GET\", \"/networkssid/\", true);\r\n";
  result += "  xhttp.send();\r\n";
  result += "}\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function displayWiFiMode() {\r\n";
  result += "var ele = document.getElementsByName('wifi');\r\n";
  result += "\r\n";
  result += "  for(i = 0; i < ele.length; i++) {\r\n";
  result += "    if(ele[i].checked) {\r\n";
  result += "       document.getElementById(ele[i].value).style.display=\"block\";\r\n";
  result += "       if (ele[i].value == 'network') {\r\n";
  result += "        document.getElementById(\"selectedWiFi\").innerHTML = \"\"\r\n";
  result += "        document.getElementById(\"selectedWiFiPassword\").style.display=\"none\"\r\n";
  result += "         loadWiFiNetworkList();\r\n";
  result += "       }\r\n";
  result += "     }\r\n";
  result += "     else {\r\n";
  result += "       document.getElementById(ele[i].value).style.display=\"none\";\r\n";
  result += "     }\r\n";
  result += "  }\r\n";
  result += "}\r\n";
  result += "displayWiFiMode();\r\n";
  result += "</script>\r\n";
  result += "</body>\r\n";
  result += "</html>\r\n";
  
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

///////////////// sse is language independent ///////////////////////////
void sse(ESP8266WebServer &server, Settings * pSettings, uint32_t revolutions, uint32_t viewPulsesPerMinute)
{
  String result = "retry: ";
  result += String(pSettings->SSE_RETRY);
  result += "\r\n";
  result += "data: ";
  result += "{";
  result += "\"revolutions\":";
  result += String(revolutions);
  result += ",";
  result += "\"viewPulsesPerMinute\":";
  result += String(viewPulsesPerMinute);
  result += "}\r\n\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/event-stream", result);

}

///////////////// Vanaf hier Nederlands ///////////////////////////
void showWiFiMode_nl(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Wifi modus wijziging is bezig zolang het middelste gele led aan, als het uit is selecteer dan de WiFi (SSID) en daarna de begin/help pagina\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<a href='/help/'>Ga naar de begin/help pagina</a>\r\n";
  result += "\r\n</body>\r\n</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void help_nl(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "<input id=\"EN\" type=\"button\" onclick=\"selectLanguage(this)\" value=\"English\">\r\n";
  result += "<input id=\"NL\" type=\"button\" onclick=\"selectLanguage(this)\" value=\"Nederlands\">\r\n";
  result += "<br><br>\r\n";
  result += "WiFi modus: ";
  if (pSettings->beginAsAccessPoint() == true)
  {
    result += "Access Point\r\n";
    result += "<br>\r\n";
    result += "(url: <a href='http://model.local/' target='_blank'>model.local</a> of <a href='http://192.168.4.1/' target='_blank'>http://192.168.4.1</a>)\r\n";
  }
  else
  {
    result += "Netwerk Station\r\n";
    result += "<br>\r\n";
    result += "(url: <a href='http://model.local/' target='_blank'>model.local</a> of via een lokaal IP adres, laatst bekende adres is: <a href='http://";
    result += pSettings->getLastNetworkIP();
    result += "/' target='_blank'>";
    result += pSettings->getLastNetworkIP();
    result += "</a>\r\n";
    result += ")\r\n";
  }  
  result += "<br>\r\n";
  result += "<div id=\"sendMessage\"></div>\r\n";
  result += "<br><br>\r\n";

  result += "Versie: <span id='version'></span>\r\n";
  result += " <input id='updateFirmwareButton' type='button' onclick='updateFirmware()' value='Update Firmware'<br>\r\n";
  result += " <div id=\"updateFirmwareMessage\"><div>\r\n";
  result += "<br><br>\r\n";

  result += "Menu\n";
  result += "<br><br><br>\r\n";
  result += "<a href='/help/'>help</a> begin/help scherm\r\n";
  result += "<br><br>\r\n";
  result += "<a href='/device/'>Model instellingen</a> WiFi modus, Server instellingen\r\n";
  result += "<br><br>\r\n";
  result += "<a href='/wifi/'>WiFi</a> instellingen om het Model te koppelen aan WiFi\r\n";
  result += "<br><br>\r\n";

  result += "<script>\r\n";
  result += "  document.getElementById(\"version\").innerHTML = \"";
  result += pSettings->getFirmwareVersion();
  result += "\";\r\n";
  result += "  function updateFirmware() {\r\n";
  result += "    document.getElementById(\"updateFirmwareButton\").disabled = true\r\n";
  result += "    document.getElementById(\"updateFirmwareMessage\").innerHTML = \"Na ongeveer 1 minuut kun je de pagina verversen\"\r\n";
  result += "    var params = \"name=update\";\r\n";
  result += "    sendUpdateFirmware(params, \"/update/\");\r\n";
  result += "  };\r\n";
  result += "</script>\r\n";

  result += "<script>\r\n";
  result += "  function selectLanguage(component) {\r\n";
  result += "    var params = \"name=help\" + \"&language=\" + component.id;\r\n";
  result += "    document.getElementById(\"NL\").disabled = true;\r\n";
  result += "    document.getElementById(\"EN\").disabled = true;\r\n";
  result += "    sendData(params, \"/language/\");\r\n";
  result += "  }\r\n";
  result += "  function sendData(data, path) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", path);\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "    //xhr.setRequestHeader(\"Content-Type\", \"application/json\");\r\n";
  result += "    document.getElementById(\"sendMessage\").innerHTML = \"Please wait\";\r\n";
  result += "    xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "      var myResponseText = \"\";\r\n";
  result += "        if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "          window.location.reload();\r\n";
  result += "        }\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "       myResponseText = this.statusText || \"\";\r\n";
  result += "      }\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";

  result += "  function sendUpdateFirmware(data, path) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", path);\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "   document.getElementById(\"sendMessage\").innerHTML = \"Please wait\";\r\n";
  result += "    xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "     var myResponseText = \"\";\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "        window.location.reload();\r\n";
  //result += "       myResponseText = this.responseText || \"\";\r\n";
  result += "     }\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "       myResponseText = this.statusText || \"\";\r\n";
  result += "      }\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";

  result += "</script>\r\n";
  result += "\r\n</body>\r\n</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void showSavedSettings_nl(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Settings\r\n";
  result += "<br><br>\r\n";
  result += "opgeslagen deviceKey: \r\n";
  result += pSettings->getDeviceKey();
  result += "\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<a href='/help/'>Ga naar de begin/help pagina</a>\r\n";
  result += "</body>\r\n";
  result += "</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void device_nl(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML><html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Instellingen voor het Model\r\n";
  result += "<br><br>\r\n";
  result += "<input type=\"radio\" name=\"settings\" onclick=\"displaySettings()\" value=\"device\" checked>Model\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"settings\" onclick=\"displaySettings()\" value=\"targetServer\">Server instellingen\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<div id=\"device\">\r\n";
  result += "    <br>\r\n";
  result += "    Set de  WiFi start modus in <input id=\"startWiFiMode\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryStartModeWiFi();
  result += "\" value=\"reset\">\r\n";
  result += "    <br>\r\n";
  result += "    <input type=\"radio\" name=\"startWiFiMode\" value=\"ap\" ";
  result += (pSettings->beginAsAccessPoint() == true)?"checked":"";
  result += "> start als Access Point\r\n";
  result += "    <br>\r\n";
  result += "    <input type=\"radio\" name=\"startWiFiMode\" value=\"network\" ";
  result += (pSettings->beginAsAccessPoint() == true)?"":"checked";
  result += "> start als Netwerk Station\r\n";
  result += "    <br><br>\r\n";
  result += "  Na 'Save' even geduld tot er een bevestiging is.\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"deviceButton\" type=\"button\" name=\"deviceButton\" value=\"Save\" onclick=\"saveDevice(this)\">\r\n";
  result += "  <input type=\"button\" name=\"deviceCancelButton\" value=\"Cancel\" onclick=\"cancelSettings()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<div id=\"targetServer\">\r\n";
  result += "    <br>\r\n";
  result += "    Server\r\n";
  result += "    <br>\r\n";
  result += "  Domein naam: <input type=\"text\" name=\"targetServer\" maxlength=\"32\" size=\"33\" placeholder=\"protocol://domein naam\" value=\"";
  result += pSettings->getTargetServer();
  result += "\"> Max 32 karakters\r\n";
  result += "    <input id=\"targetServer\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryTargetServer();
  result += "\" value=\"reset\">\r\n";
  result += "    <br>\r\n";
  result += "    Poort: <input type=\"text\" name=\"targetPort\" min=\"0\" max=\"65536\" maxlength=\"5\" size=\"6\" placeholder=\"poort\" title=\"0 - 65536\" value=\"";
  result += String(pSettings->getTargetPort());
  result += "\"  onkeyup=\"checkNumber(this, 'portMessage', 'Invalid counter (0 - 65536)');\">\r\n";
  result += "    <input id=\"targetPort\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += String(pSettings->getFactoryTargetPort());
  result += "\" value=\"reset\">\r\n";
  result += "    <span id=\"portMessage\"></span>\r\n";
  result += "    <br>\r\n";
  result += "    Pad: <input type=\"text\" name=\"targetPath\" maxlength=\"16\" size=\"17\" placeholder=\"pad\" value=\"";
  result += pSettings->getTargetPath();
  result += "\"> Max 16 karakters\r\n";
  result += "    <input id=\"targetPath\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryTargetPath();
  result += "\" value=\"reset\">\r\n";
  result += "  <br><br>\r\n";
  result += "  Na 'Save' even geduld tot er een bevestiging is.\r\n";
  result += "    <br>\r\n";
  result += "  <input id=\"targetServerButton\" type=\"button\" name=\"targetServerButton\" value=\"Save\" onclick=\"saveTargetServer(this)\">\r\n";
  result += "  <input type=\"button\" name=\"targetServerCancelButton\" value=\"Cancel\" onclick=\"cancelSettings()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<br>\r\n";
  result += "<div id=\"sendMessage\"></div>\r\n";
  result += "\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<a href='/help/'>Ga naar de begin/help pagina</a>\r\n";
  result += "<script>\r\n";
  result += "  function factorySetting(component) {\r\n";
  result += "      var id = component.id || \"\";\r\n";
  result += "      var factoryValue = component.getAttribute(\"reset\");\r\n";
  result += "      var names = document.getElementsByName(id) || [];\r\n";
  result += "      if (names.length > 0) {\r\n";
  result += "        var type = names[0].getAttribute(\"type\");\r\n";
  result += "        if (type == \"radio\")\r\n";
  result += "        {\r\n";
  result += "            for (var i = 0; i < names.length; i++)\r\n";
  result += "            {\r\n";
  result += "                if (names[i].value == factoryValue) {\r\n";
  result += "                    names[i].checked = true;\r\n";
  result += "                };\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        if (type == \"checkbox\")\r\n";
  result += "        {\r\n";
  result += "            var factoryValueArray = factoryValue.split(\",\");\r\n";
  result += "            for (var i = 0; i < names.length; i++)\r\n";
  result += "            {\r\n";
  result += "                names[i].checked = false;\r\n";
  result += "                for (var e = 0; e < factoryValueArray.length; e++)\r\n";
  result += "                {\r\n";
  result += "                    if (names[i].value == factoryValueArray[e].trim()) {\r\n";
  result += "                        names[i].checked = true;\r\n";
  result += "                    }\r\n";
  result += "                }\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        if (type == \"text\")\r\n";
  result += "        {\r\n";
  result += "            names[0].value = factoryValue;\r\n";
  result += "        }\r\n";
  result += "      }\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function cancelSettings() {\r\n";
  result += "  window.location.reload();\r\n";
  result += "  }\r\n";
  result += "  function sendData(data) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", \"/deviceSettings/\");\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "    //xhr.setRequestHeader(\"Content-Type\", \"application/json\");\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = \"Even geduld\";\r\n";
  result += "      xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "        var myResponseText = \"\";\r\n";
  result += "        if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "          myResponseText = this.responseText || \"\";\r\n";
  result += "        }\r\n";
  result += "        if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "          myResponseText = this.statusText || \"\";\r\n";
  result += "        }\r\n";
  result += "        document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "      }\r\n";
  //result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveDevice(content) {\r\n";
  result += "        var children = content.parentNode.childNodes;\r\n";
  result += "        var startWiFiMode = \"\";\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"startWiFiMode\") {\r\n";
  result += "                if (children[i].checked == true) {\r\n";
  result += "                    startWiFiMode = children[i].value || true;\r\n";
  result += "                }\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        var params = \"name=device\" + \"&startWiFiMode=\" + startWiFiMode;\r\n";
  result += "        sendData(params);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveTargetServer(content) {\r\n";
  result += "        var children = content.parentNode.childNodes;\r\n";
  result += "        var targetServer = \"\";\r\n";
  result += "        var targetPort = \"\";\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"targetServer\") {\r\n";
  result += "                targetServer = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"targetPort\") {\r\n";
  result += "                targetPort = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"targetPath\") {\r\n";
  result += "                targetPath = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        var params = \"name=targetServer\" + \"&targetServer=\" + encodeURIComponent(targetServer) + \"&targetPort=\" + targetPort + \"&targetPath=\" + encodeURIComponent(targetPath);\r\n";
  result += "        sendData(params);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function loadWiFiNetworkList() {\r\n";
  result += "  var xhttp = new XMLHttpRequest();\r\n";
  result += "  xhttp.onreadystatechange = function() {\r\n";
  result += "    if (this.readyState == 4 && this.status == 200) {\r\n";
  result += "      document.getElementById(\"ssidList\").innerHTML = this.responseText;\r\n";
  result += "    }\r\n";
  result += "  };\r\n";
  result += "  xhttp.open(\"GET\", \"/networkssid/\", true);\r\n";
  result += "  xhttp.send();\r\n";
  result += "}\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function displaySettings() {\r\n";
  result += "var ele = document.getElementsByName('settings');\r\n";
  result += "\r\n";
  result += "  for(i = 0; i < ele.length; i++) {\r\n";
  result += "    if(ele[i].checked) {\r\n";
  result += "      document.getElementById(ele[i].value).style.display=\"block\";\r\n";
  result += "//      if (ele[i].value == 'network') {\r\n";
  result += "//        loadWiFiNetworkList();\r\n";
  result += "//      }\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "      document.getElementById(ele[i].value).style.display=\"none\";\r\n";
  result += "    }\r\n";
  result += "  }\r\n";
  result += "}\r\n";
  result += "displaySettings();\r\n";
  result += "</script>\r\n";
  result += "</body>\r\n";
  result += "</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void wifi_nl(ESP8266WebServer &server, Settings * pSettings, WiFiSettings * pWiFiSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>model</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Wil gegevens niet delen met internet of geen WiFi beschikbaar? Kies AccessPoint\r\n";
  result += "<br>\r\n";
  result += "Wil gegevens delen met internet en er is WiFi beschibaar? Kies Netwerk Station\r\n";
  result += "<br><br>\r\n";
  result += "<input type=\"radio\" name=\"wifi\" onclick=\"displayWiFiMode()\" value=\"ap\">Access Point\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"wifi\" onclick=\"displayWiFiMode()\" value=\"network\">Netwerk Station\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"wifi\" onclick=\"displayWiFiMode()\" value=\"erase\">Ga naar Verwijder WiFi-gegevens menu\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<div id=\"ap\">\r\n";
  result += "  Apparaten kunnen toegang krijgen tot dit Access Point met het hieronder ingevulde SSID en wachtwoord\r\n";
  result += "  <br>\r\n";
  result += "  Een niet-ingevuld SSID geeft het standaard SSID van het Access Point\r\n";
  result += "  <br>\r\n";
  result += "  Een niet-ingevuld wachtwoord geeft een onveilige, open Access Point\r\n";
  result += "  <br>\r\n";
  result += "  SSID: <input type=\"text\" name=\"ssid\" maxlength=\"32\" size=\"33\" placeholder=\"";
  if (pWiFiSettings->getAccessPointSSID() == "")
  {
    result += "SSID";
  }
  else
  {
    result += pWiFiSettings->getAccessPointSSID();
  }
  result += "\" value=\"";
  result += pWiFiSettings->getAccessPointSSID();
  result += "\">\r\n";
  result += "  <br>\r\n";
  result += "  Wachtwoord: <input type=\"password\" name=\"password\" maxlength=\"32\" size=\"33\" placeholder=\"";
  if (pWiFiSettings->getAccessPointPassword() == "")
  {
    result += "wachtwoord";
  }
  else
  {
    result += pWiFiSettings->getAccessPointPassword();
  }
  result += "\" value=\"";
  result += pWiFiSettings->getAccessPointPassword();
  result += "\" onkeyup=\"checkURIComponent(this, 'apPasswordMessage', 'Ongeldig wachtwoord karakter');\">\r\n";
  result += " <span id=\"apPasswordMessage\"></span>\r\n";
  result += "  <br><br>\r\n";
  result += "  Na 'Save' even geduld tot er een bevestiging is.\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"apButton\" type=\"button\" name=\"apButton\" value=\"Save\" onclick=\"saveAP(this)\">\r\n";
  result += "  <input type=\"button\" name=\"apCancelButton\" value=\"Cancel\" onclick=\"cancelWiFi()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<div id=\"network\">\r\n";
  result += "  Maak verbinding met een van de WiFi netwerken hieronder\r\n";
  result += "  <br><br>\r\n";
  result += "  <span id=\"ssidList\">Wacht even tot er een lijst of een melding verschijnt</span>\r\n";
  result += "  <br><br>\r\n";
  result += "  <span id=\"selectedWiFiPassword\">";
  result += "Geef het wachtwoord voor het geselecteerde WiFi netwerk <span id=\"selectedWiFi\"></span>\r\n";
  result += "     <br>\r\n";
  result += "     Wachtwoord: <input type=\"password\" name=\"password\" maxlength=\"32\" size=\"33\" placeholder=\"password\" value=\"";
  result += "\" onkeyup=\"checkURIComponent(this, 'networkPasswordMessage', 'Ongeldig wachtwoord karakter');\">\r\n";
  result += "     <br><br>\r\n";
  result += "  </span>\r\n";
  result += "  Na 'Save' even geduld tot er een bevestiging is.\r\n";
  result += "  <br>\r\n";
  result += "   <input id=\"networkButton\" type=\"button\" name=\"networkButton\" value=\"Save\" onclick=\"saveNetwork(this)\">\r\n";
  result += "   <input type=\"button\" name=\"networkCancelButton\" value=\"Cancel\" onclick=\"cancelWiFi()\">\r\n";
  result += "  <span id=\"networkPasswordMessage\"></span>\r\n";
  result += "</div>\r\n";
  result += "<div id=\"erase\">\r\n";
  result += "  !!!Opgelet!!!\r\n";
  result += "  <br><br>\r\n";
  result += "  Een klik op de 'Erase' knop zal onmiddellijk de opgeslagen gegevens verwijderen! De huidige verbinding blijft bestaan.\r\n";
  result += "  <br><br>\r\n";
  result += "Verwijder NIETS en <input type=\"button\" name=\"networkButton\" value=\"Cancel\" onclick=\"cancelWiFi()\">\r\n";
  result += "  <br><br>\r\n";
  result += "  <input id=\"eraseAPData\" type=\"button\" name=\"eraseAPDataButton\" value=\"Erase\" onclick=\"eraseWiFiData(this)\"> Verwijderen van Access Point resulteert in in een onveilig, open Access Point\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"eraseNetworkData\" type=\"button\" name=\"eraseNetworkDataButton\" value=\"Erase\" onclick=\"eraseWiFiData(this)\"> Verwijder Netwerk gegevens\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"eraseWiFiData\" type=\"button\" name=\"eraseWiFiDataButton\" value=\"Erase\" onclick=\"eraseWiFiData(this)\"> Verwijder Access Point EN Netwerk gegevens\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "  <br>\r\n";
  result += "<div id=\"sendMessage\"></div>\r\n";
  result += "\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<a href='/help/'>Ga naar de begin/help pagina</a>\r\n";
  result += "<script>\r\n";
  result += "function checkURIComponent(component, messageId, message) {\r\n";
  result += "  var invalidCharacterArray = [\"&\"]\r\n";
  result += "  var buttonNodeId = component.parentNode.id;\r\n";
  result += "  if (buttonNodeId == \"selectedWiFiPassword\") {\r\n";
  result += "    buttonNodeId = component.parentNode.parentNode.id;\r\n";
  result += "  };\r\n";
  result += "  var buttonId = buttonNodeId + \"Button\"\r\n";
  result += "   var valid = true;\r\n";
  result += "   for (var c = 0; c < invalidCharacterArray.length; c++) {\r\n";
  result += "    if (component.value.indexOf(invalidCharacterArray[c]) > -1) {\r\n";
  result += "      valid = false;\r\n";
  result += "      break;\r\n";
  result += "    };\r\n";
  result += "  };\r\n";
  result += "  if (valid) {\r\n";
  result += "    document.getElementById(messageId).innerHTML = \"\";\r\n";
  result += "  }\r\n";
  result += "  else {\r\n";
  result += "    document.getElementById(messageId).innerHTML = message;\r\n";
  result += "  }\r\n";
  result += "  document.getElementById(buttonId).disabled = !valid;\r\n";
  result += "   return valid;\r\n";
  result += "}\r\n";
  result += "  function cancelWiFi() {\r\n";
  result += "    window.location.reload();\r\n";
  result += "  }\r\n";
  result += "  function sendData(data) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", \"/wifiConnect/\");\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "    //xhr.setRequestHeader(\"Content-Type\", \"application/json\");\r\n";
  result += "   document.getElementById(\"sendMessage\").innerHTML = \"Even geduld\";\r\n";
  result += "    xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "     var myResponseText = \"\";\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "       myResponseText = this.responseText || \"\";\r\n";
  result += "     }\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "       myResponseText = this.statusText || \"\";\r\n";
  result += "      }\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveAP(content) {\r\n";
  result += "    var children = content.parentNode.childNodes;\r\n";
  result += "    var ssid = \"\";\r\n";
  result += "    var password = \"\";\r\n";
  result += "    for (var i = 0; i < children.length; i++) {\r\n";
  result += "      if (children[i].name == \"ssid\") {\r\n";
  result += "        ssid = children[i].value || \"\";\r\n";
  result += "      }\r\n";
  result += "      if (children[i].name == \"password\") {\r\n";
  result += "        password = children[i].value || \"\";\r\n";
  result += "      }\r\n";
  result += "    }\r\n";
  result += "    var params = \"name=ap\" + \"&ssid=\" + ssid + \"&password=\" + password;\r\n";
  result += "    sendData(params);\r\n";
  result += "    //var json_upload = JSON.stringify({name:\"ap\", ssid:ssid, password:password});\r\n";
  result += "    //sendData(json_upload);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveNetwork(content) {\r\n";
  result += "    var children = document.getElementById(\"selectedWiFiPassword\").childNodes;\r\n";
  result += "    var ssid = document.getElementById(\"selectedWiFi\").innerHTML;\r\n";
  result += "    var password = \"\";\r\n";
  result += "    for (var i = 0; i < children.length; i++) {\r\n";
  result += "      if (children[i].name == \"password\") {\r\n";
  result += "        password = children[i].value || \"\";\r\n";
  result += "      }\r\n";
  result += "    }\r\n";
  result += "    var params = \"name=network\" + \"&ssid=\" + ssid + \"&password=\" + password;\r\n";
  result += "    sendData(params);\r\n";
  result += "    //var json_upload = JSON.stringify({name:\"network\", ssid:ssid, password:password});\r\n";
  result += "    //sendData(json_upload);\r\n";
  result += "  }\r\n";
  result += "  function eraseWiFiData(content) {\r\n";
  result += "  var params = \"name=erase\" + \"&target=\" + content.id;\r\n";
  result += "      sendData(params);\r\n";
  result += "  }\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";

  result += "function showNetworkList(networks) {\r\n";
  result += "  var showNetworkList = [];\r\n";
  result += "  var showNetwork = \"\";\r\n";
  result += "  var networkList = (new Function(\"return [\" + networks + \"];\")());\r\n";
  result += "  networkList.sort((a,b) => (a.dBm > b.dBm) ? 1: (a.dBm === b.dBm) ? ((a.ssid > b.ssid) ? 1: -1) : -1);\r\n";
  result += "  networkList = networkList.filter(function(e) { return e.dBm > -80});\r\n";
  result += "  sortedList = [...networkList].reverse();\r\n";
  result += "  for (var key in sortedList) {\r\n";
  result += "    var value = sortedList[key]\r\n";
  result += "    showNetworkList.push(Object.values(value)[0]);\r\n";
  result += "  }\r\n";
  result += "  var uniqueShowNetworkList = [...new Set(showNetworkList)];\r\n";
  result += "  for (var key in uniqueShowNetworkList) {\r\n";
  result += "    showNetwork += \"<div>\" + uniqueShowNetworkList[key] + \"</div>\";\r\n";
  result += "  }\r\n";
  result += "  if (showNetwork == \"\") {\r\n";
  result += "    showNetwork = \"Geen WiFi signaal beschikbaar\"\r\n";
  result += "  }\r\n";
  result += "  else {\r\n";
  result += "    document.getElementById(\"selectedWiFiPassword\").style.display=\"block\"\r\n";
  result += "  }\r\n";
  result += "  document.getElementById(\"ssidList\").innerHTML = showNetwork;\r\n";
  result += "}\r\n"; 
  result += "function selectNetworkSSID(content) {\r\n";
  result += "  ssid = \"\"\r\n";
  result += "  if (content.name == \"networkSSID\") {\r\n";
  result += "    ssid = content.value;\r\n";
  result += "  }\r\n";
  result += "  document.getElementById(\"selectedWiFi\").innerHTML = ssid;\r\n";
  result += "}\r\n";
  result += "function loadWiFiNetworkList() {\r\n";
  result += "  var xhttp = new XMLHttpRequest();\r\n";
  result += "  xhttp.onreadystatechange = function() {\r\n";
  result += "    if (this.readyState == 4 && this.status == 200) {\r\n";
  result += "      showNetworkList(this.responseText);\r\n";
  result += "    }\r\n";
  result += "  };\r\n";
  result += "  xhttp.open(\"GET\", \"/networkssid/\", true);\r\n";
  result += "  xhttp.send();\r\n";
  result += "}\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function displayWiFiMode() {\r\n";
  result += "var ele = document.getElementsByName('wifi');\r\n";
  result += "\r\n";
  result += "  for(i = 0; i < ele.length; i++) {\r\n";
  result += "    if(ele[i].checked) {\r\n";
  result += "       document.getElementById(ele[i].value).style.display=\"block\";\r\n";
  result += "       if (ele[i].value == 'network') {\r\n";
  result += "        document.getElementById(\"selectedWiFi\").innerHTML = \"\"\r\n";
  result += "        document.getElementById(\"selectedWiFiPassword\").style.display=\"none\"\r\n";
  result += "         loadWiFiNetworkList();\r\n";
  result += "       }\r\n";
  result += "     }\r\n";
  result += "     else {\r\n";
  result += "       document.getElementById(ele[i].value).style.display=\"none\";\r\n";
  result += "     }\r\n";
  result += "  }\r\n";
  result += "}\r\n";
  result += "displayWiFiMode();\r\n";
  result += "</script>\r\n";
  result += "</body>\r\n";
  result += "</html>\r\n";
  
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}
